browser=chrome
baseUrl=https://trueclaim-fe.onrender.com/
apiBaseUrl=https://trueclaim-iks6.onrender.com/
implicitWait=10
explicitWait=30
# API Testing
#testEmail=devansh@gmail.com
#testPassword=123456
testEmail=agent@gmail.com
testPassword=12345678
role = agent
